# Generated by Django 3.2 on 2024-03-31 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userfollow_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollow',
            name='fans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fans', to=settings.AUTH_USER_MODEL, verbose_name='粉丝'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='focus', to=settings.AUTH_USER_MODEL, verbose_name='关注'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='likes',
            field=models.OneToOneField(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='获赞'),
        ),
    ]
