# Generated by Django 3.2 on 2024-03-31 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240331_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollow',
            name='likes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_likes', to=settings.AUTH_USER_MODEL, verbose_name='获赞'),
        ),
    ]
