# Generated by Django 3.2 on 2024-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userfollow_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.FileField(default='/media/33.jpg', max_length=255, upload_to='', verbose_name='头像'),
        ),
    ]
