# Generated by Django 3.2 on 2024-03-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_user_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('path', models.CharField(max_length=255, verbose_name='访问路径')),
                ('duration', models.IntegerField(default=0, verbose_name='访问视图时间,ms')),
                ('response_type', models.CharField(max_length=255, verbose_name='响应类型')),
                ('status', models.IntegerField(default=200, verbose_name='响应状态码')),
                ('is_success', models.BooleanField(default=False, verbose_name='响应是否成功')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
                'ordering': ['operate_time'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='nation',
            field=models.CharField(blank=True, default='Austria', max_length=255, null=True, verbose_name='国籍'),
        ),
    ]
