# Generated by Django 3.2 on 2024-04-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240331_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollow',
            name='fans',
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan', to=settings.AUTH_USER_MODEL, verbose_name='关注'),
        ),
    ]
