# Generated by Django 3.2 on 2024-03-28 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('video_file', models.FileField(max_length=255, upload_to='', verbose_name='视频文件')),
                ('video_icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='预览图片')),
                ('display_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='播放时长')),
                ('display_times', models.IntegerField(blank=True, null=True, verbose_name='播放次数')),
                ('released', models.BooleanField(default=False, verbose_name='是否发布成功')),
                ('intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='视频简介')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to=settings.AUTH_USER_MODEL, verbose_name='视频发布者')),
            ],
            options={
                'verbose_name': '所有视频',
                'verbose_name_plural': '所有视频',
                'db_table': 'videos',
                'ordering': ['create_time'],
            },
        ),
    ]
