# Generated by Django 3.2 on 2024-03-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='owner',
            new_name='author',
        ),
    ]
