# Generated by Django 3.2 on 2024-03-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='play_times',
            field=models.IntegerField(default=0, verbose_name='播放次数'),
        ),
    ]
